

const cardRankings = [
    ['Dont use', -1],
    ['Club', 2],
    ['Dia', 2],
    ['Heart', 2],
    ['Spade', 2],
    ['Club', 3],
    ['Dia', 3],
    ['Heart', 3],
    ['Spade', 3],
    ['Club', 4],
    ['Dia', 4],
    ['Heart', 4],
    ['Spade', 4],
    ['Club', 5],
    ['Dia', 5],
    ['Heart', 5],
    ['Spade', 5],
    ['Club', 6],
    ['Dia', 6],
    ['Heart', 6],
    ['Spade', 6],
    ['Club', 7],
    ['Dia', 7],
    ['Heart', 7],
    ['Spade', 7],
    ['Club', 8],
    ['Dia', 8],
    ['Heart', 8],
    ['Spade', 8],
    ['Club', 9],
    ['Dia', 9],
    ['Heart', 9],
    ['Spade', 9],
    ['Club', 10],
    ['Dia', 10],
    ['Heart', 10],
    ['Spade', 10],
    ['Club', 11],
    ['Dia', 11],
    ['Heart', 11],
    ['Spade', 11],
    ['Club', 12],
    ['Dia', 12],
    ['Heart', 12],
    ['Spade', 12],
    ['Club', 13],
    ['Dia', 13],
    ['Heart', 13],
    ['Spade', 13],
    ['Club', 14],
    ['Dia', 14],
    ['Heart', 14],
    ['Spade', 14]
  ];

  export default cardRankings;